# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 17:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('Meal_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Meal_Category', models.CharField(choices=[(b'Breakfast', b'Breakfast'), (b'Lunch', b'Lunch'), (b'Dinner', b'Dinner')], default=b'Breakfast', max_length=30)),
                ('Date', models.DateField()),
                ('Meal_No_Tip', models.FloatField()),
                ('Meal_Tip', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('Trip_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Contact_Person', models.CharField(max_length=200)),
                ('Place', models.CharField(max_length=200)),
                ('Purpose', models.CharField(max_length=200)),
                ('Date_Left', models.DateField()),
                ('Date_Returned', models.DateField()),
                ('Time_Left', models.TimeField()),
                ('Time_Returned', models.TimeField()),
                ('Traveler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
