# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 21:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='Date_Left',
            new_name='Date_Departed',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='Time_Left',
            new_name='Time_Departed',
        ),
    ]
